First working version with metrics !

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -1,6 +1,162 @@
-version: '3.4'
+version: '3.8'
 
 services:
+    setup:
+        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+        volumes:
+            - certs:/usr/share/elasticsearch/config/certs
+        user: '0'
+        command: >
+            bash -c '
+            if [ x${ELASTIC_PASSWORD} == x ]; then
+                echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
+                exit 1;
+            elif [ x${KIBANA_PASSWORD} == x ]; then
+                echo "Set the KIBANA_PASSWORD environment variable in the .env file";
+                exit 1;
+            fi;
+            if [ ! -f config/certs/ca.zip ]; then
+                echo "Creating CA";
+                bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
+                unzip config/certs/ca.zip -d config/certs;
+            fi;
+            if [ ! -f config/certs/certs.zip ]; then
+                echo "Creating certs";
+                echo -ne \
+                "instances:\n"\
+                "  - name: es01\n"\
+                "    dns:\n"\
+                "      - es01\n"\
+                "      - localhost\n"\
+                "    ip:\n"\
+                "      - 127.0.0.1\n"\
+                "  - name: kibana\n"\
+                "    dns:\n"\
+                "      - kibana\n"\
+                "      - localhost\n"\
+                "    ip:\n"\
+                "      - 127.0.0.1\n"\
+                > config/certs/instances.yml;
+                bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
+                unzip config/certs/certs.zip -d config/certs;
+            fi;
+            echo "Setting file permissions"
+            chown -R root:root config/certs;
+            find . -type d -exec chmod 750 \{\} \;;
+            find . -type f -exec chmod 640 \{\} \;;
+            echo "Waiting for Elasticsearch availability";
+            until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
+            echo "Setting kibana_system password";
+            until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
+            echo "All done!";
+            '
+        healthcheck:
+            test: ['CMD-SHELL', '[ -f config/certs/es01/es01.crt ]']
+            interval: 1s
+            timeout: 5s
+            retries: 120
+
+    es01:
+        depends_on:
+            setup:
+                condition: service_healthy
+        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+        container_name: h3micro_elasticsearch
+        labels:
+            co.elastic.logs/module: elasticsearch
+        volumes:
+            - certs:/usr/share/elasticsearch/config/certs
+            - esdata01:/usr/share/elasticsearch/data
+        ports:
+            - ${ES_PORT}:9200
+        environment:
+            - node.name=es01
+            - cluster.name=${CLUSTER_NAME}
+            - discovery.type=single-node
+            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
+            - bootstrap.memory_lock=true
+            - xpack.security.enabled=true
+            - xpack.security.http.ssl.enabled=true
+            - xpack.security.http.ssl.key=certs/es01/es01.key
+            - xpack.security.http.ssl.certificate=certs/es01/es01.crt
+            - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
+            - xpack.security.transport.ssl.enabled=true
+            - xpack.security.transport.ssl.key=certs/es01/es01.key
+            - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
+            - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
+            - xpack.security.transport.ssl.verification_mode=certificate
+            - xpack.license.self_generated.type=${LICENSE}
+        mem_limit: ${ES_MEM_LIMIT}
+        ulimits:
+            memlock:
+                soft: -1
+                hard: -1
+        healthcheck:
+            test:
+                [
+                    'CMD-SHELL',
+                    "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
+                ]
+            interval: 10s
+            timeout: 10s
+            retries: 120
+
+    kibana:
+        depends_on:
+            es01:
+                condition: service_healthy
+        image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
+        container_name: h3micro_kibana
+        labels:
+            co.elastic.logs/module: kibana
+        volumes:
+            - certs:/usr/share/kibana/config/certs
+            - kibanadata:/usr/share/kibana/data
+        ports:
+            - ${KIBANA_PORT}:5601
+        environment:
+            - SERVERNAME=kibana
+            - ELASTICSEARCH_HOSTS=https://es01:9200
+            - ELASTICSEARCH_USERNAME=kibana_system
+            - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
+            - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
+            - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
+            - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
+            - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
+        mem_limit: ${KB_MEM_LIMIT}
+        healthcheck:
+            test:
+                [
+                    'CMD-SHELL',
+                    "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
+                ]
+            interval: 10s
+            timeout: 10s
+            retries: 120
+
+    metricbeat01:
+        depends_on:
+            es01:
+                condition: service_healthy
+            kibana:
+                condition: service_healthy
+        image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
+        user: root
+        volumes:
+            - certs:/usr/share/metricbeat/certs
+            - metricbeatdata01:/usr/share/metricbeat/data
+            - './metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro'
+            - '/var/run/docker.sock:/var/run/docker.sock:ro'
+            - '/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro'
+            # - '/proc:/hostfs/proc:ro'
+            # - '/:/hostfs:ro'
+        environment:
+            - ELASTIC_USER=elastic
+            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
+            - ELASTIC_HOSTS=https://es01:9200
+            - KIBANA_HOSTS=http://kibana:5601
+            - LOGSTASH_HOSTS=http://logstash01:9600
+
     db:
         image: postgres
         container_name: h3micro_db
@@ -55,9 +211,9 @@ services:
 
         depends_on:
             - db
-            - elasticsearch
-            - logstash
-            - kibana
+            # - elasticsearch
+            # - logstash
+            # - kibana
 
     reverse_proxy_server:
         image: nginx
@@ -137,58 +293,73 @@ services:
             - h3micronetwork
         restart: on-failure
 
-    elasticsearch:
-        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
-        container_name: h3micro_elasticsearch
-        # volumes:
-        #     - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
-        environment:
-            - discovery.type=single-node
-            - xpack.security.enabled=false
-            - ES_JAVA_OPTS=-Xms1g -Xmx1g
-        ports:
-            - '9200:9200'
-            - '9300:9300'
-        networks:
-            - h3micronetwork
-        restart: on-failure
-        depends_on:
-            - cadvisor
+    # elasticsearch:
+    #     image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
+    #     container_name: h3micro_elasticsearch
+    #     # volumes:
+    #     #     - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
+    #     environment:
+    #         - discovery.type=single-node
+    #         - xpack.security.enabled=false
+    #         - ES_JAVA_OPTS=-Xms1g -Xmx1g
+    #     ports:
+    #         - '9200:9200'
+    #         - '9300:9300'
+    #     networks:
+    #         - h3micronetwork
+    #     restart: on-failure
+    #     depends_on:
+    #         - cadvisor
 
-    logstash:
-        image: docker.elastic.co/logstash/logstash:8.11.3
-        container_name: h3micro_logstash
-        ports:
-            - '9600:9600'
-            - '8089:8089'
-            - '5044:5044'
-        volumes:
-            - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
-            - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
-        environment:
-            xpack.monitoring.enabled: 'true'
-        networks:
-            - h3micronetwork
-        restart: on-failure
-        depends_on:
-            - elasticsearch
+    # logstash:
+    #     image: docker.elastic.co/logstash/logstash:8.11.3
+    #     container_name: h3micro_logstash
+    #     ports:
+    #         - '9600:9600'
+    #         - '8089:8089'
+    #         - '5044:5044'
+    #     volumes:
+    #         - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
+    #         - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
+    #     environment:
+    #         xpack.monitoring.enabled: 'true'
+    #     networks:
+    #         - h3micronetwork
+    #     restart: on-failure
+    #     depends_on:
+    #         - elasticsearch
 
-    kibana:
-        image: kibana:8.11.3
-        container_name: kibana
-        # volumes:
-        #     - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
-        environment:
-            - ELASTICSEARCH_HOSTS=http://h3micro_elasticsearch:9200
-            - xpack.fleet.agents.enabled=false
-        ports:
-            - '5601:5601'
-        networks:
-            - h3micronetwork
-        depends_on:
-            - elasticsearch
-            - logstash
-        restart: always
+    # kibana:
+    #     image: kibana:8.11.3
+    #     container_name: kibana
+    #     # volumes:
+    #     #     - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
+    #     environment:
+    #         - ELASTICSEARCH_HOSTS=http://h3micro_elasticsearch:9200
+    #         - xpack.fleet.agents.enabled=false
+    #     ports:
+    #         - '5601:5601'
+    #     networks:
+    #         - h3micronetwork
+    #     depends_on:
+    #         - elasticsearch
+    #         - logstash
+    #     restart: always
+
 networks:
     h3micronetwork:
         driver: bridge
+
+volumes:
+    certs:
+        driver: local
+    esdata01:
+        driver: local
+    kibanadata:
+        driver: local
+    metricbeatdata01:
+        driver: local
+    filebeatdata01:
+        driver: local
+    logstashdata01:
+        driver: local
